<?php
/**
 * @file gatekeeper_extras.module
 * defines some examples of how you can use gatekeeper, this examples work
 */

/**
 * Implements hook_regsiter_power()
 */
function gatekeeper_extras_register_power() {
	return array(
		'tweet',
		'postToFacebook',
	);
}
 
/**
 * Implements hook_register_gate()
 */
function gatekeeper_extras_register_gate() {
	$gates = array();
	// Define the options
	$gates["platform"]["options"] = array(
		"development", "production"
	);
	// Define the callback to call for validation
	$gates["platform"]["callback"] = "_gatekeeper_platform";
	
	$gates["role"] = array(
		'options' => array(
			'god',
			'isadmin',
			'all',
			'registered',
			'anonymous',
		),
		'callback' => "_gatekeeper_role"
	);
	
	// Language gate
	$gates["lang"] = array(
		'options' => language_list(),
		'callback' => "_gatekeeper_lang"
	);
	
	$gates["timezone"] = array(
		'options' => system_time_zones(FALSE),
		'callback' => "_gatekeeper_timezone"
	);
	
	return $gates;
}

/**
 * Gate by platform
 */
function _gatekeeper_platform($options) {
	$access = FALSE;
	if($options == "development") {
		// check if the current site is the development version
		if(variable_get("siteversion") == "development") {
			$access = TRUE;
		}
	}
	elseif($options == "production") {
		if(variable_get("siteversion") == "production") {
			$access = TRUE;
		}
	}
	else {
		$access = FALSE;
	}
	
	return $access;
}

/**
 * Gate by user role
 */
function _gatekeeper_role($options) {
	global $user;
	$access = FALSE;
	switch($options) {
		case "god":
			if($user->uid == 1) {
				$access = TRUE;
			}
			break;
		
		case "all":
			$access = TRUE;
			break; 
			
		case "anonymous":
			if(user_is_anonymous()) {
				$access = TRUE;
			}
			break;
		
		case "registered":
			if(user_is_logged_in()) {
				$access = TRUE;
			}
			break;
		
		case "isadmin":
			if(user_access("administer site")) {
				$access = TRUE;
			}
			break;
	}
	
	return $access;
}

/**
 * Gate by language
 */
function _gatekeeper_lang($option) {
	$access = FALSE;
	if(drupal_multilingual()) {
		global $user;
		
		if($option == $user->language) {
			$access = TRUE;
		}
	}

	return $access;
}

/**
 * Gate by timezone
 */
function _gatekeeper_timezone($option) {
	$timezone = drupal_get_user_timezone();
	$access = FALSE;
	if($option == $timezone) {
		$access = TRUE;
	}
		
	return $access;	
}
